export enum AuthAction {
  LOGOUT_USER = 'LOGOUT_USER',
  SET_PROFILE = 'SET_PROFILE',
  SET_DELIVERY_ADDRESS = 'SET_DELIVERY_ADDRESS',
  SET_CART = 'SET_CART',
  SET_TRANSACTION = 'SET_TRANSACTION',
  SET_PLACED_ORDERS = 'SET_PLACED_ORDERS',
  SET_SELL_HISTORY = 'SET_SELL_HISTORY',
  SET_ORDER_DETAILS = 'SET_ORDER_DETAILS',
  SET_OTHER_USER = 'SET_OTHER_USER',
}
