export enum UiAction {
  FORM_START = 'FORM_START',
  FORM_SUCCESS = 'FORM_SUCCESS',
  FORM_FAIL = 'FORM_FAIL',
  DATA_START = 'DATA_START',
  DATA_END = 'DATA_END',
  TRADE_START = 'TRADE_START',
  TRADE_END = 'TRADE_END',
  SET_MESSAGE = 'SET_MESSAGE',
  SET_MODAL = 'SET_MODAL',
  SET_PRODUCTS_PER_PAGE = 'SET_PRODUCTS_PER_PAGE',
}
